const jobPosts = [
    {
        id: 1,
        title: "Banking customer managements system development",
        objective: "Develop a banking app using the following simplicity tips: Minimize the number of functions (an app should fulfill the primary needs of users; you may also build separate simple apps to perform different functions ",
        budget: 4500,
        date: "10th April 2020",
        keywords: ["ios", "android", "django"],
        Location: 'Los Angeles',
        visibility: 1,
        status: 1,
    },
    {
        id: 2,
        title: "iOS app design",
        objective: "Seeking ui/ux app designer to put together prototype of an application in the next 1-2 weeks. Must have iOS design experience and sign company NDA. Please submit a link to your portfolio and explain your process (e.g. what you need from us).",
        budget: 2600,
        date: "19th May 2020",
        keywords: ["blockchain", "data analytics", "programming"],
        Location: 'Rome',
        visibility: 2,
        status: 1,
    },
    {
        id: 3,
        title: "Facebook and Linkedin Ads",
        objective: "Create and manage a Facebook and Linkedin marketing campaign. Very specific audience. Also generate landing pages and set up email marketing campaigns.",
        budget: 1400,
        date: "9th June 2020",
        keywords: ["Facebook", "Google", "Ads"],
        Location: 'Germany',
        visibility: 1,
        status: 1,
    },
    {
        id: 4,
        title: "React Native Developer",
        objective: "Join us to create our new iOS and Android applications. You will be part of the definition and implementation of this challenging project from its ground up..",
        budget: 4400,
        date: "4th June 2020",
        keywords: ["React", "Design", "Android"],
        Location: 'San Fransisco',
        visibility: 1,
        status: 1,
    },
    {
        id: 5,
        title: "Banking software development",
        objective: "Leverage existing technology solutions to create scalable banking application.banking app. Choose reliable data storage. Don't store sensitive data, passwords, and transaction-related information on the device.",
        budget: 4500,
        date: "10th April 2020",
        keywords: ["android", "mobile apps", "programming"],
        Location: 'Florida',
        visibility: 1,
        status: 1,

    },
    {
        id: 6,
        title: "iOS app design",
        objective: "Seeking ui/ux app designer to put together prototype of an application in the next 1-2 weeks. Must have iOS design experience and sign company NDA. Please submit a link to your portfolio and explain your process (e.g. what you need from us).",
        budget: 2600,
        date: "19th May 2020",
        keywords: ["ios", "android", "API"],
        Location: 'Miami',
        visibility: 1,
        status: 1,
    },
]

export default jobPosts;